### ISSUE TITLE
deleting Special rules cause wfptool.exe crash

### ISSUE THREAD

**Issue by hesss5** [henrypp/wfptool#13]
let say i created five Special rules
then if try to delete first 4 of rule wfptool.exe will  crashed
but if i start delete rules from last rule everything fine

thanks

**Comment by henrypp** [comment]
done

**Comment by hesss5** [comment]
still crash,crash after click apply button
 Problem Event Name:	APPCRASH
  Application Name:	wfptool.exe
  Application Version:	1.3.6.0
  Application Timestamp:	58315362
  Fault Module Name:	wfptool.exe
  Fault Module Version:	1.3.6.0
  Fault Module Timestamp:	58315362
  Exception Code:	40000015
  Exception Offset:	0002783b
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1065
  Additional Information 1:	a20d
  Additional Information 2:	a20d5492477447eb5be28120f2029682
  Additional Information 3:	54ec
  Additional Information 4:	54eca1dec5e48b524d427b3e84913e24

**Comment by henrypp** [comment]
i see ;(

**Comment by henrypp** [comment]
done pt.2
